name: pii-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.11
  - pip=25.1
  - pip:
      - fastapi
      - uvicorn
      - python-multipart
      - pdfminer-six
      - torch==2.2.2
      - transformers==4.55.4
      - tokenizers==0.21.4
      - huggingface-hub==0.34.4
      - safetensors
      - requests
      - tqdm
      - regex
      - numpy==1.26.4
